### ISSUE TITLE
"Server cannot be reached" state causes high CPU load

### ISSUE THREAD

**Issue by schickling** [prismagraphql/graphql-playground#627]
When the server can't be reached the Playground causes very high CPU load – is this caused by the (SVG) animation? If so, how could this be implemented more efficiently?

![image](https://user-images.githubusercontent.com/1567498/38195299-289abbca-367d-11e8-9e0a-80a34333fdad.png)
![image](https://user-images.githubusercontent.com/1567498/38195316-3cab8496-367d-11e8-84e1-46b732c77f71.png)

**Comment by kachkaev** [comment]
Yeah, looks like graphql-playground is just endlessly re-rendering itself even when there's no interaction. Here's a Chrome performance report for my [graphql-yoga](https://github.com/graphcool/graphql-yoga) UI instance:

<img width="696" alt="screen shot 2018-04-09 at 21 25 58" src="https://user-images.githubusercontent.com/608862/38521189-dedd4082-3c3c-11e8-8981-64e44a98da98.png">

<img width="324" alt="screen shot 2018-04-09 at 21 26 15" src="https://user-images.githubusercontent.com/608862/38521203-eb47f7d6-3c3c-11e8-9cc8-7f7c1580fdf0.png">

**Comment by mdmasumbillah** [comment]
I have same problem

**Comment by timsuchanek** [comment]
Thanks for reporting!
Because of this we recently disabled the animation for this screen.
This should fix the performance issue for now.
![image.png](https://images.zenhubusercontent.com/5a0d9e5e8a75884b9087afda/54bf16fd-7d0c-41f0-84dc-f6cf9552b415)

**Comment by wulffeld** [comment]
@timsuchanek I'm using the latest 1.6.2 and it's still a problem. Or is this fix not included in 1.6.2?

**Comment by bazaglia** [comment]
Running 1.6.2 and it stills an issue. It makes my MacBook Pro (2015) really really slow! I don't know why this issue was closed. @timkendall any update?
