### ISSUE TITLE
Adding auth headers to playground middleware programmatically ( not via UI ) not working

### ISSUE THREAD

**Issue by arjunrao87** [prismagraphql/graphql-playground#788]
#### This issue pertains to the following package(s):

- [ ] GraphQL Playground - Electron App
- [ ] GraphQL Playground HTML
- [ ] GraphQL Playground
- [x] GraphQL Playground Express Middleware
- [ ] GraphQL Playground Hapi Middleware
- [ ] GraphQL Playground Koa Middleware
- [ ] GraphQL Playground Lambda Middleware

#### What OS and OS version are you experiencing the issue(s) on?
Mac OS Sierra

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?
1.7.2

#### What is the expected behavior?
When I add headers to the playground middleware, it gets picked up downstream.
```
  playground(({ headers: {'Authorization': 'qux'},
                          endpoint: '/graphql'}))
```
req.headers.authorization should be qux

#### What is the actual behavior?
The auth headers are not picked up and req.headers.authorization is undefined

#### What steps may we take to reproduce the behavior?
Recreate the above scenario and check the value of req.headers.authorization in the /graphql router

_Please provide a gif or image of the issue for a quicker response/fix._

**Comment by arjunrao87** [comment]
Can someone help out with this?

**Comment by amazzoccone** [comment]
Oh! I really need this too! 🙏

**Comment by fabiancook** [comment]
This can be achieved by adding a `header` query parameter to your endpoint.

The header parameter is parsed as a JSON string and passed along with all future requests. 

For example this is what I am using with serverless/lambda to pass an `"Authorization"` header:

```js
export function handler(event, lambdaContext, callback) {
  lambdaContext.callbackWaitsForEmptyEventLoop = false;
  if (event.httpMethod !== 'GET') {
    //_this.playgroundHandler(event, lambdaContext, callback);
    return instance.graphqlHandler(event, lambdaContext, callback);
  }
  const options = {
    endpoint: '/'
  };
  if (event.requestContext && event.requestContext.authorizer && event.requestContext.authorizer.token) {
    const headers = {
      Authorization: `Bearer ${event.requestContext.authorizer.token}`
    };
    options.endpoint += `?headers=${encodeURIComponent(JSON.stringify(headers))}`;
  }
  return lambdaPlayground(options)(event, lambdaContext, callback);
}

**Comment by cleverplatypus** [comment]
@huv1k headers parameter still ignored in version 1.7.31

**Comment by mdv27** [comment]
Facing same issue, @arjunrao87 is solution given by @fabiancook working for you?

**Comment by mdv27** [comment]
Issue fixed with Azure AD Auth provider. It inserts idToken on successful login to all application pages in my case. If there is any change required to incoming requests before /graphql API call like getting On Behalf Of token ([OBO](https://learn.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-on-behalf-of-flow)) using incoming header idToken then `middleware` approach works. Express has similar support as [nestjs](https://docs.nestjs.com/middleware).

**Comment by KenEucker** [comment]
Are header parameters still not working? I am using `@graphql-yoga/node@^3.1.2`. With the serialized header example from @fabiancook, I am not getting the Authorization header inside the playground or when I run queries.
